import { flowerGen } from "./flowerGen.js";
import { addSoloonsAndComets } from "./soloonsAndComeths.js";
import { cleanBoard, updateCelestials } from "../utils/updateRemote.js";
import createHtmlMap from "../utils/render.js";
import "../config.js";
const initialMap = new Array(30).fill([]).map(()=>new Array(30).fill("SPACE"));
const flowerGenExample = () => flowerGen(initialMap, 1, 1);
const sprinkled = addSoloonsAndComets(flowerGenExample());
createHtmlMap(sprinkled, "./lib/Phase2/flowerGen.html");
updateCelestials(sprinkled).then((res)=>console.log(res));
